#pragma once
#include <Arduino.h>
static const char UI[] PROGMEM = R"SOILUI(<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Soil / Valve</title><style>
:root{font:16px system-ui,sans-serif;color:#e7f0e8;background:#101b18;color-scheme:dark}*{box-sizing:border-box}body{max-width:1160px;margin:auto;padding:30px 22px}header{display:flex;justify-content:space-between;align-items:center;gap:20px}h1{font-size:30px;letter-spacing:-1px;margin:0}h2{font-size:18px;margin:0 0 16px}p{color:#a9bdb2;line-height:1.5}.tag{font-size:12px;letter-spacing:2px;color:#96d8ae}.pill{border:1px solid #466052;border-radius:30px;padding:8px 14px;font-size:13px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin:26px 0}.card,section{background:#192923;border:1px solid #30483b;border-radius:16px;padding:22px}.label{color:#a9bdb2;font-size:13px}.value{font-size:32px;margin:10px 0}small{color:#a9bdb2}.grid{display:grid;grid-template-columns:2fr 1fr;gap:16px}canvas{width:100%;height:280px;display:block}button{border:1px solid #557c63;border-radius:8px;background:#274534;color:#f0fff4;padding:11px 15px;cursor:pointer;font:inherit}button:hover{background:#395e46}button:disabled{opacity:.45;cursor:not-allowed}.stop{background:#623932;border-color:#b97665}.buttons{display:flex;gap:9px;flex-wrap:wrap;margin:16px 0}input{width:100%;padding:9px;margin-top:5px;background:#101b18;border:1px solid #54705f;border-radius:6px;font:inherit}label{display:block;color:#b6cbbd;font-size:13px}form .fields{display:grid;grid-template-columns:1fr 1fr;gap:12px}.alert{padding:12px;border-radius:8px;background:#473c25;color:#ffdea0;margin:12px 0}.ok{background:#214c35;color:#b8f0c7}#events{max-height:370px;overflow:auto;padding:0;list-style:none}#events li{padding:12px 0;border-bottom:1px solid #30483b;font-size:14px}#events time{display:block;font-size:11px;color:#91a799;margin-bottom:5px}section+section{margin-top:16px}footer{font-size:12px;color:#8fa598;margin:24px 0}#message{min-height:24px;color:#ffdea0}.legend{display:flex;justify-content:space-between;font-size:12px;color:#a9bdb2}.demo{background:#755222;color:white;padding:10px;text-align:center;margin-bottom:20px;border-radius:8px}@media(max-width:760px){.grid{grid-template-columns:1fr}.cards{grid-template-columns:1fr}.value{font-size:26px}header{align-items:start}.card{padding:16px}}
</style></head><body>
<div id="demo" class="demo" hidden>DEMO · simulated data · controls disabled · no hardware connected</div>
<header><div><div class="tag">GROW / OBSERVE / CONTROL</div><h1>Soil / Valve</h1><p>Moisture monitoring & bounded irrigation</p></div><span class="pill" id="connection">Connecting…</span></header>
<div id="banner" class="alert" role="status" aria-live="polite">Waiting for the controller.</div>
<div class="cards"><div class="card"><div class="label">RELATIVE MOISTURE</div><div class="value" id="moisture">—</div><small id="raw">ADC — mV</small></div><div class="card"><div class="label">VALVE COMMAND</div><div class="value" id="valve">Unknown</div><small>No position feedback fitted</small></div><div class="card"><div class="label">AUTOMATIC WATERING</div><div class="value" id="mode">Unknown</div><small id="budget">—</small></div></div>
<div class="grid"><div><section><h2>Moisture history</h2><div class="legend"><span>Relative moisture (%) · green</span><span>Thresholds · dashed</span></div><canvas id="chart" role="img" aria-label="Moisture history relative to low and high thresholds"></canvas><div class="legend"><span>Elapsed time since boot (hours)</span><button id="csv">Export CSV</button></div><p>One sample per minute, up to 24 hours. History is held in RAM and clears on restart or recalibration. This is a relative index, not volumetric water content.</p></section>
<section><h2>Valve control</h2><p>Automatic mode starts below the low threshold and stops at the high threshold. Each pulse lasts at most 5 seconds, followed by at least 60 seconds of soak time.</p><div class="buttons"><button data-action="arm">Arm automatic</button><button data-action="pulse">Single 5 s pulse</button><button data-action="close" class="stop">Close & disarm</button><button data-action="reset">Reset fault</button></div><div id="message" role="status" aria-live="polite"></div><small>Physical STOP must be released and its normally closed loop connected. Restart always disarms automatic watering.</small></section>
<section><h2>Calibration & thresholds</h2><p>Disarm first. Record the displayed ADC millivolts in representative dry and wet soil, then save both endpoints. Saving clears history so different calibrations are never mixed.</p><form id="settings"><div class="fields"><label>Dry endpoint (mV)<input id="dryMv" type="number" min="300" max="2150" step="0.1" required></label><label>Wet endpoint (mV)<input id="wetMv" type="number" min="100" max="1950" step="0.1" required></label><label>Low threshold (%)<input id="low" type="number" min="5" max="90" step="0.1" required></label><label>High threshold (%)<input id="high" type="number" min="10" max="95" step="0.1" required></label></div><div class="buttons"><button type="submit">Save calibration & thresholds</button></div></form></section></div>
<section><h2>Thresholds & events</h2><p>In-page notifications, including alerts received while this page was closed. The latest 32 controller events are retained until restart.</p><ul id="events" aria-live="polite"></ul></section></div>
<footer>Prototype Rev A · Local access point · Verify valve travel and flow before connecting water. A CLOSED command does not prove the valve is shut.</footer>
<script>
'use strict';
const $=id=>document.getElementById(id), demo=new URLSearchParams(location.search).has('demo');
let state=null,points=[],initialized=false,lastBoot='',lastHistory=0,online=false,busy=false;
function controls(){document.querySelectorAll('[data-action],#settings button').forEach(b=>b.disabled=demo||!online||busy);}
function draw(){const c=$('chart'),r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=280*d;const x=c.getContext('2d');x.scale(d,d);const w=r.width,h=280,L=40,R=12,T=18,B=32;
const end=Math.max(60,state?.s||60),start=Math.max(0,end-86400),px=s=>L+(s-start)/(end-start)*(w-L-R),py=v=>T+(100-v)/100*(h-T-B);
x.font='11px system-ui';x.lineWidth=1;
for(let v=0;v<=100;v+=25){x.strokeStyle='#31483d';x.beginPath();x.moveTo(L,py(v));x.lineTo(w-R,py(v));x.stroke();x.fillStyle='#a9bdb2';x.fillText(v,7,py(v)+4);}
for(let i=0;i<=4;i++){const s=start+(end-start)*i/4;x.fillText((s/3600).toFixed(end-start<3600?2:1),px(s)-8,h-9);}
if(state){x.setLineDash([5,5]);for(const v of [state.low,state.high]){x.strokeStyle='#e6c884';x.beginPath();x.moveTo(L,py(v));x.lineTo(w-R,py(v));x.stroke();}x.setLineDash([]);}
x.strokeStyle='#8fe0a7';x.lineWidth=2;x.beginPath();let active=false;for(const p of points){if(p.s<start||p.pct===null){active=false;continue;}if(!active){x.moveTo(px(p.s),py(p.pct));active=true;}else x.lineTo(px(p.s),py(p.pct));}x.stroke();
x.fillStyle='#8fe0a7';for(const p of points){if(p.s>=start&&p.pct!==null){x.beginPath();x.arc(px(p.s),py(p.pct),1.5,0,Math.PI*2);x.fill();}}
}
function render(s){state=s;$('connection').textContent=demo?'Demo mode':'Controller online';$('moisture').textContent=s.valid?s.moisture.toFixed(1)+' %':'Uncalibrated / invalid';$('raw').textContent='ADC '+s.mv.toFixed(1)+' mV';$('valve').textContent=s.open?'OPEN':'CLOSED';$('mode').textContent=s.armed?'Armed':'Disarmed';$('budget').textContent=s.reservedSeconds+' / 30 s reserved; quiet-hour reset';
const alert=s.fault||(!s.storageOK?'Configuration storage error':!s.calibrated?'Calibration required before watering':!s.valid?'Waiting for valid sensor samples':s.moisture<s.low?'LOW moisture · below start threshold':s.moisture>=s.high?'HIGH moisture · stop threshold reached':'Moisture is within the threshold band');$('banner').textContent=alert;$('banner').className=s.valid&&!s.fault&&s.storageOK&&s.moisture>=s.low?'alert ok':'alert';
if(!initialized){for(const k of ['dryMv','wetMv','low','high'])$(k).value=s[k];initialized=true;}
$('events').replaceChildren(...s.events.slice().reverse().map(e=>{const li=document.createElement('li'),t=document.createElement('time');t.textContent=(e.s/3600).toFixed(2)+' h after boot';li.append(t,document.createTextNode(e.message));return li;}));draw();controls();}
async function get(path){const r=await fetch(path,{cache:'no-store',signal:AbortSignal.timeout(5000)});if(!r.ok)throw Error('Controller HTTP '+r.status);return r.json();}
async function refresh(){if(demo)return;try{const s=await get('/api/status');if(lastBoot&&s.boot!==lastBoot){initialized=false;points=[];lastHistory=0;}lastBoot=s.boot;online=true;render(s);if(Date.now()-lastHistory>15000){points=await get('/api/history');lastHistory=Date.now();draw();}}catch(e){online=false;$('connection').textContent='Offline / stale';$('banner').textContent='Connection lost. Displayed values may be stale. Armed automation continues on the controller; use the physical STOP if needed.';$('banner').className='alert';}controls();}
async function post(path,body){busy=true;controls();try{const r=await fetch(path,{method:'POST',headers:{'X-Control-Token':state.token},body:new URLSearchParams(body),signal:AbortSignal.timeout(5000)});const text=await r.text();$('message').textContent=text;if(!r.ok)throw Error(text);lastHistory=0;await refresh();}catch(e){$('message').textContent=e.message+' — verify actual controller status.';}finally{busy=false;controls();}}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>post('/api/command',{action:b.dataset.action}));
$('settings').onsubmit=e=>{e.preventDefault();post('/api/config',Object.fromEntries(['dryMv','wetMv','low','high'].map(k=>[k,$(k).value])));};
$('csv').onclick=()=>{const rows=['seconds_since_boot,relative_moisture_pct,adc_mv,valve_command_open',...points.map(p=>[p.s,p.pct??'',p.mv,p.open].join(','))];const url=URL.createObjectURL(new Blob([rows.join('\n')],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download=(demo?'DEMO-':'')+'soil-history.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
window.addEventListener('resize',draw);
if(demo){$('demo').hidden=false;points=Array.from({length:721},(_,i)=>({s:i*60,pct:48-20*Math.sin(i/95)+2*Math.sin(i/9),mv:1200,open:false}));online=true;render({s:43200,moisture:points.at(-1).pct,mv:1200,valid:true,armed:false,open:false,fault:'',storageOK:true,calibrated:true,low:30,high:55,dryMv:1600,wetMv:850,reservedSeconds:10,events:[{s:0,message:'DEMO: illustrative moisture history'},{s:19800,message:'LOW moisture threshold crossed'},{s:19801,message:'Valve commanded OPEN'},{s:19806,message:'Valve commanded CLOSED'},{s:38000,message:'HIGH moisture threshold reached'}]});}else{refresh();setInterval(refresh,2000);}controls();
</script></body></html>
)SOILUI";
